site_name: ONS Onboarding Documentation
nav:
  - Welcome: index.md
  - Getting Started:
    - Setting up Your Workstation: getting_started/workstation.md
    - Accessing ONS Systems: getting_started/access.md
  - Company Policies and Guidelines:
    - Code of Conduct: policies/code_of_conduct.md
    - Security Policies: policies/security.md
    - Data Protection Guidelines: policies/data_protection.md
  - Tools and Resources:
    - Project Management Tools: tools/project_management.md
    - Document Collaboration: tools/document_collaboration.md
    - Source Control: tools/source-control.md
    - Training Tools: tools/training-tools.md
  - Training and Development:
    - Mandatory Training Modules: training/mandatory_training.md
    - Career Development Resources: training/career_development.md
  - FAQs: faqs.md
theme:
  name: material
